### ISSUE TITLE
asan doesn't compile on Linux with GCC 4.4

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#146]
Originally reported on Google Code with ID 146

```
What steps will reproduce the problem?
1. Checkout llvm sources rev. 173675  (but could also be reproduced with earlier versions)
2. Try to compile everything using cmake and gcc4.4

What is the expected output? What do you see instead?

It should compile without error. But I get :

[ 19%] /tmp/llvm/projects/compiler-rt/lib/msan/msan_allocator.cc:36:error: ‘__msan::cache’
cannot be thread-local because it has non-POD type ‘__msan::AllocatorCache’
cc1plus: warning: unrecognized command line option "-Wno-c99-extensions"
make[2]: *** [projects/compiler-rt/lib/msan/CMakeFiles/clang_rt.msan-x86_64.dir/msan_allocator.cc.o]
Error 1
make[1]: *** [projects/compiler-rt/lib/msan/CMakeFiles/clang_rt.msan-x86_64.dir/all]
Error 2
make[1]: *** Waiting for unfinished jobs....

FYI I'm using these options for cmake :

cmake -DLLVM_BUILD_32_BITS=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON

What version of the product are you using? On what operating system?

❯ uname -a
Linux linux-job 2.6.32-5-amd64 #1 SMP Wed Jan 12 03:40:32 UTC 2011 x86_64 GNU/Linux

❯ gcc --version
gcc (Debian 4.4.5-8) 4.4.5
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Reported by `mkvtoolnix.build.jonthn` on 2013-01-28 08:20:32
